project_crm/crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from  crm.views import home,depart,user
urlpatterns = [
    url(r'^index/$', home.index),
    url(r'^depart/list/$', depart.depart_list),
    url(r'^depart/add/$', depart.depart_add),
    url(r'^depart/edit/(\d+)/', depart.depart_edit),
    url(r'^depart/del/(\d+)/$', depart.depart_del),

    url(r'^user/list/$', user.user_list),
    url(r'^user/add/$', user.user_add),
    url(r'^user/edit/(\d+)/', user.user_edit),
    url(r'^user/del/(\d+)/', user.user_del),
]

project_crm/project_crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crm/', include('crm.urls')),
]

project_crm/crm/models.py
from django.db import models

# Create your models here.
class DepartMent(models.Model):
    """
    部门表
    """
    title = models.CharField(verbose_name="部门名称",max_length=32)
    def __str__(self):
        return self.title

class UserInfo(models.Model):
    """
    用户表
    """
    username = models.CharField(verbose_name="用户名",max_length=32)
    password = models.CharField(verbose_name="密码",max_length=64)
    email = models.EmailField(verbose_name='邮箱',max_length=128)
    gender_choice = (
        (1,'男'),
        (2,'女'),
    )
    gender = models.IntegerField(verbose_name='性别',choices=gender_choice)
    depart = models.ForeignKey(verbose_name="所在部门",to='DepartMent')

project_crm/crm/forms/depart.py
from crm  import  models
from django.forms import ModelForm
from django import  forms
class DepartModelForm(ModelForm):
    class Meta:
        model = models.DepartMent
        fields = "__all__"
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control','placeholder':'部门名称'})
        }
        error_messages = {
            'title':{
                'required':'部门名称不能为空'
            }
        }

project_crm/crm/forms/user.py
from django import  forms
from  crm import  models
class UserModelForm(forms.ModelForm):
    class Meta:
        model = models.UserInfo
        fields = "__all__"
        widgets = {
            'username':forms.TextInput(attrs={"class":"form-control","placeholder":"用户名"}),
            'password':forms.TextInput(attrs={"class":"form-control","placeholder":"密码"}),
            'email':forms.EmailInput(attrs={"class":"form-control","placeholder":"邮箱"}),
            'gender':forms.Select(attrs={"class":"form-control"}),
            'depart':forms.Select(attrs={"class":"form-control","placeholder":"所在部门"}),
        }
        error_messages = {
            'username': {
                'required': '用户名不能为空'
            },
            'password': {
                'required': '密码不能为空'
            },
            'email': {
                'required': '邮箱不能为空',
                'invalid':'邮箱格式不正确',
            },
            'gender': {
                'required': '请选择性别'
            },
            'depart': {
                'required': '请选择部门'
            },
        }

project_crm/crm/views/depart.py
from django.shortcuts import render,redirect
from crm  import  models
from crm.forms.depart import DepartModelForm
from crm.views import my_page
import time
def depart_list(request):
    """
    部门列表
    :param request:
    :return:
    """
    # 从url获取页码数，若没有则默认取第一页
    try:
        page_num = request.GET.get("page")
    except Exception as e:
        page_num = 1
    # 获取总数据
    totle_count = models.DepartMent.objects.all().count()
    page = my_page.Page(page_num, totle_count, per_pag=5, url_prefix="/crm/depart/list/", max_page=11)
    depart_queryset = models.DepartMent.objects.all()[page.data_start:page.data_end]
    page_html = page.page_html()
    return render(request,'depart_list.html',{"depart_queryset":depart_queryset,"page_html":page_html})

def depart_add(request):
    if request.method == "GET":
        form = DepartModelForm()
        return render(request, 'depart_form.html', {"form":form})
    form = DepartModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/crm/depart/list/')
    return render(request, 'depart_form.html', {"form":form})

def depart_edit(request,nid):
    obj = models.DepartMent.objects.filter(id=nid).first()
    if request.method == "GET":
        form = DepartModelForm(instance=obj)
        return render(request,'depart_form.html',{"form":form})
    form = DepartModelForm(data=request.POST,instance=obj)
    if form.is_valid():
        form.save()
        return redirect('/crm/depart/list/')
    return render(request,'depart_form.html',{"form":form})

def depart_del(request,nid):
    # time.sleep(1)
    # nid = request.POST.get("id")
    models.DepartMent.objects.filter(id=nid).delete()
    return redirect('/crm/depart/list/')

project_crm/crm/views/home.py
from django.shortcuts import render
def index(request):
    return  render(request,'index.html')

project_crm/crm/views/my_page.py
from django.shortcuts import render, redirect, HttpResponse
from crm import models
class Page(object):
    def __init__(self,page_num,totle_count,url_prefix,per_pag=2,max_page=11):
        self.url_prefix = url_prefix
        self.max_page = max_page
        # 算出总共需要多少页码来展示数据
        totle_page, m = divmod(totle_count, per_pag)
        if m:
            totle_page += 1
        self.totle_page = totle_page
        # 如果总的页码数超过了最大页码数，默认返回最后一页，当输入的密码不是正经数字，则返回第一页
        try:
            page_num = int(page_num)
            if page_num > totle_page:
                page_num = totle_page
        except Exception as e:
            page_num = 1
        self.page_num = page_num
        # 定义数据从哪取到哪
        self.data_start = (page_num - 1) * per_pag
        self.data_end = page_num * per_pag
        half_max_page = self.max_page // per_pag
        # 页面上的数据页也从哪开始
        page_start = page_num - half_max_page
        # 页面上的数据页从哪结束
        page_end = page_num + half_max_page
        # 如果总页码数小于最大页码数，则最大页码数等于总页码数
        if totle_page < self.max_page:
            self.max_page = totle_page
            # 如果当前页减一半比1小
        if page_start <= 1:
            page_start = 1
            page_end = self.max_page
        # 如果当前页加一半比总页码还大
        if page_end >= totle_page:
            page_end = totle_page
            page_start = totle_page - self.max_page + 1
        self.page_start = page_start
        self.page_end = page_end
    @property
    def start(self):
        return self.data_start
    @property
    def end(self):
        return self.data_end
    def page_html(self):
        # 自己拼接分页的HTML页码
        html_str_list = []
        # 加上第一页
        html_str_list.append('<li><a href="{}?page=1">首页</a></li>'.format(self.url_prefix))
        # 上一页 如果第一页 就没有上一页
        if self.page_num <= 1:
            html_str_list.append('<li class="disabled"><a href="#"><span aria-hidden="true">&laquo;</span></a></li>')
        else:
            html_str_list.append(
                '<li><a href="{}?page={}"><span aria-hidden="true">&laquo;</span></a></li>'.format(self.url_prefix,self.page_num - 1))
        for i in range(self.page_start, self.page_end + 1):
            # 如果是当前页就加active类
            if i == self.page_num:
                tmp = '<li class="active"><a href="{0}?page={1}">{1}</a></li>'.format(self.url_prefix,i)
            else:
                tmp = '<li><a href="{0}?page={1}">{1}</a></li>'.format(self.url_prefix,i)
            html_str_list.append(tmp)
        # 下一页
        if self.page_num >= self.totle_page:
            html_str_list.append('<li class="disabled"><a href="#"><span aria-hidden="true">&raquo;</span></a></li>')
        else:
            html_str_list.append(
                '<li><a href="{}?page={}"><span aria-hidden="true">&raquo;</span></a></li>'.format(self.url_prefix,self.page_num + 1))
        # 加最后一页
        html_str_list.append('<li><a href="{}?page={}">尾页</a></li>'.format(self.url_prefix,self.totle_page))
        page_html = "".join(html_str_list)
        return page_html

project_crm/crm/views/user.py
from django.shortcuts import render,redirect
from crm import models
from crm.forms.user import UserModelForm
from crm.views import my_page
def user_list(request):
    # 从url获取页码数，若没有则默认取第一页
    try:
        page_num = request.GET.get("page")
    except Exception as e:
        page_num = 1
    # 获取总数据
    totle_count = models.UserInfo.objects.all().count()
    page = my_page.Page(page_num, totle_count, per_pag=5, url_prefix="/crm/user/list/", max_page=11)
    user_queryset = models.UserInfo.objects.all()[page.data_start:page.data_end]
    page_html = page.page_html()
    return render(request,'user_list.html',{"user_queryset":user_queryset,"page_html":page_html})

def user_add(request):
    if request.method == "GET":
        form = UserModelForm()
        return render(request, 'user_form.html', {"form":form})
    form = UserModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return  redirect('/crm/user/list/')
    return render(request, 'user_form.html', {"form":form})

def user_edit(request,nid):
    obj = models.UserInfo.objects.filter(id=nid).first()
    if request.method == "GET":
        form = UserModelForm(instance=obj)
        return render(request, 'user_form.html', {"form":form})
    form = UserModelForm(data=request.POST,instance=obj)
    if form.is_valid():
        form.save()
        return redirect('/crm/user/list/')
    return render(request, 'user_form.html', {"form":form})

def user_del(request,nid):
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect('/crm/user/list/')

project_crm/crm/templates/depart_form.html
{% extends 'layout.html' %}

{% block content %}
    <form class="form-horizontal" method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label class="col-sm-2 control-label">{{ form.title.label }}</label>
            <div class="col-sm-10">
                {{ form.title }}
                <span style="color: red;">{{ form.title.errors.0 }}</span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" class="btn btn-primary" value="提 交">
            </div>
        </div>
    </form>
{% endblock %}

project_crm/crm/templates/depart_list.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin: 5px;">
        <a href="/crm/depart/add/" class="btn btn-primary"><i class="fa fa-plus-circle" aria-hidden="true"></i> 添加</a>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>名称</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for row in depart_queryset %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.title }}</td>
                    <td>
                        <a href="/crm/depart/edit/{{ row.id }}/"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                        |
                        <a href="/crm/depart/del/{{ row.id }}/" style="color: red;">
{#                        <button class="del">#}
                             <i class="fa fa-trash-o" aria-hidden="true"></i>
{#                        </button>#}
{#                        <button type="button" class="btn btn-default btn-xs del "><span#}
{#                                            class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>#}

                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="bot">
        <nav aria-label="Page navigation">
            <ul class="pagination pagination-lg"
                style="float: right;margin-right: 50px;margin-top: 50px;">
                {{ page_html|safe }}
            </ul>
        </nav>
    </div>
{#    {% load staticfiles %}#}
{#    <script>#}
{#    // 找到删除按钮绑定事件#}
{#    $(".del").on("click", function () {#}
{#        var $trEle = $(this).parent().parent();#}
{#        var delId = $trEle.children().eq(0).text();#}
{#        swal({#}
{#                title: "你确定要删除吗？",#}
{#                text: "一旦删除就找不回来了哦",#}
{#                type: "warning",#}
{#                showCancelButton: true,#}
{#                confirmButtonClass: "btn-warning",#}
{#                confirmButtonText: "确认",#}
{#                cancelButtonText: "取消",#}
{#                closeOnConfirm: false,#}
{#                showLoaderOnConfirm: true#}
{#            },#}
{#            function () {#}
{#                // 向后端发送删除的请求#}
{#                $.ajax({#}
{#                    url: "/crm/depart/del/",#}
{#                    type: "post",#}
{#                    data: {"id": delId},#}
{#                    success: function (arg) {#}
{#                        swal(arg, "Del Successful", "success");#}
{#                        $trEle.remove();#}
{#                    }#}
{#                });#}
{#            });#}
{#    })#}
{#</script>#}
{% endblock %}

project_crm/crm/templates/index.html
{% extends 'layout.html' %}
{%  block content %}
    <h1>欢迎登陆</h1>
{% endblock %}

project_crm/crm/templates/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>路飞学城</title>
    <link rel="shortcut icon" href="{% static 'imgs/luffy-study-logo.png' %} ">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %} "/>
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/commons.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/nav.css' %} "/>
    {#<script src="{% static 'js/jquery-3.3.1.min.js' %} "></script>#}
    {#<script src="{% static 'plugins/bootstrap/js/bootstrap.js' %} "></script>#}
    {#<script src="{% static 'jquery-3.3.1.js' %}"></script>#}
    {#<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>#}
    {#<script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>#}
    {#<script src="{% static 'setupajax.js' %}"></script>#}
    <link  rel="stylesheet" href="{% static 'js/jquery-3.3.1.min.js' %}"/>
    <link  rel="stylesheet" href="{% static 'plugins/bootstrap/js/bootstrap.js' %}"/>
    <link  rel="stylesheet" href="{% static 'jquery-3.3.1.js' %}"/>
    <link  rel="stylesheet" href="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"/>
    <link  rel="stylesheet" href="{% static 'sweetalert/sweetalert.min.js' %}"/>
    <link  rel="stylesheet" href="{% static 'setupajax.js' %}"/>
    <style>
        body {
            margin: 0;
        }

        .no-radius {
            border-radius: 0;
        }

        .no-margin {
            margin: 0;
        }

        .pg-body > .left-menu {
            background-color: #EAEDF1;
            position: absolute;
            left: 1px;
            top: 48px;
            bottom: 0;
            width: 220px;
            border: 1px solid #EAEDF1;
            overflow: auto;
        }

        .pg-body > .right-body {
            position: absolute;
            left: 225px;
            right: 0;
            top: 48px;
            bottom: 0;
            overflow: scroll;
            border: 1px solid #ddd;
            border-top: 0;
            font-size: 13px;
            min-width: 755px;
        }

        .navbar-right {
            float: right !important;
            margin-right: -15px;
        }

        .luffy-container {
            padding: 15px;
        }

        .left-menu .menu-body .static-menu {

        }

        .left-menu .menu-body .static-menu .icon-wrap {
            width: 20px;
            display: inline-block;
            text-align: center;
        }

        .left-menu .menu-body .static-menu a {
            text-decoration: none;
            padding: 8px 15px;
            border-bottom: 1px solid #ccc;
            color: #333;
            display: block;
            background: #efefef;
            background: -webkit-gradient(linear, left bottom, left top, color-stop(0, #efefef), color-stop(1, #fafafa));
            background: -ms-linear-gradient(bottom, #efefef, #fafafa);
            background: -o-linear-gradient(bottom, #efefef, #fafafa);
            filter: progid:dximagetransform.microsoft.gradient(startColorStr='#e3e3e3', EndColorStr='#ffffff');
            -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorStr='#fafafa',EndColorStr='#efefef')";
            box-shadow: inset 0 1px 1px white;
        }

        .left-menu .menu-body .static-menu a:hover {
            color: #2F72AB;
            border-left: 2px solid #2F72AB;
        }

        .left-menu .menu-body .static-menu a.active {
            color: #2F72AB;
            border-left: 2px solid #2F72AB;
        }
    </style>
    {% block css %} {% endblock %}
</head>
<body>

<div class="pg-header">
    <div class="nav">
        <div class="logo-area left">
            <a href="#">
                <img class="logo" src="{% static 'imgs/logo.svg' %}">
                <span style="font-size: 18px;">路飞学城 </span>
            </a>
        </div>

        <div class="left-menu left">
            <a class="menu-item">资产管理</a>
            <a class="menu-item">用户信息</a>
            <a class="menu-item">路飞管理</a>
            <div class="menu-item">
                <span>使用说明</span>
                <i class="fa fa-caret-down" aria-hidden="true"></i>
                <div class="more-info">
                    <a href="#" class="more-item">管他什么菜单</a>
                    <a href="#" class="more-item">实在是编不了</a>
                </div>
            </div>
        </div>

        <div class="right-menu right clearfix">

            <div class="user-info right">
                <a href="#" class="avatar">
                    <img class="img-circle" src="{% static 'imgs/default.png' %}">
                </a>

                <div class="more-info">
                    <a href="#" class="more-item">个人信息</a>
                    <a href="#" class="more-item">注销</a>
                </div>
            </div>

            <a class="user-menu right">
                消息
                <i class="fa fa-commenting-o" aria-hidden="true"></i>
                <span class="badge bg-success">2</span>
            </a>

            <a class="user-menu right">
                通知
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                <span class="badge bg-success">2</span>
            </a>

            <a class="user-menu right">
                任务
                <i class="fa fa-bell-o" aria-hidden="true"></i>
                <span class="badge bg-danger">4</span>
            </a>
        </div>

    </div>
</div>
<div class="pg-body">
    <div class="left-menu">
        <div class="menu-body">
            <div class="static-menu">
                <a href="/crm/depart/list/"><span class="icon-wrap"><i class="fa fa-map-o" aria-hidden="true"></i></span> 部门管理</a>
                <a href="/crm/user/list/"><span class="icon-wrap"><i class="fa fa-address-book" aria-hidden="true"></i></span> 用户管理</a>
{#                <a href="#"><span class="icon-wrap"><i class="fa fa-map-o" aria-hidden="true"></i></span> 部门管理</a>#}
            </div>
        </div>
    </div>
    <div class="right-body">
        <div>
            <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">

                <li><a href="#">首页</a></li>
                <li class="active">客户管理</li>

            </ol>
        </div>
        {% block content %} {% endblock %}
    </div>
</div>



{% block js %} {% endblock %}
</body>
</html>

project_crm/crm/templates/user_form.html
{% extends 'layout.html' %}

{% block content %}
    <form class="form-horizontal" method="post" novalidate>
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">
                {{ field }}
                <span style="color: red;">{{ field.errors.0 }}</span>
            </div>
        </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" class="btn btn-primary" value="提 交">
            </div>
        </div>
    </form>
{% endblock %}

project_crm/crm/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div style="margin: 5px;">
        <a href="/crm/user/add/" class="btn btn-primary"><i class="fa fa-plus-circle" aria-hidden="true"></i> 添加</a>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>用户名</th>
                <th>密码</th>
                <th>邮箱</th>
                <th>性别</th>
                <th>所在部门</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for row in user_queryset %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.username }}</td>
                    <td>{{ row.password }}</td>
                    <td>{{ row.email }}</td>
                    <td>{{ row.get_gender_display }}</td>
                    <td>{{ row.depart.title }}</td>
                    <td>
                        <a href="/crm/user/edit/{{ row.id }}/"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                        |
                        <a href="/crm/user/del/{{ row.id }}/" style="color: red;"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="bot">
        <nav aria-label="Page navigation">
            <ul class="pagination pagination-lg"
                style="float: right;margin-right: 50px;margin-top: 50px;">
                {{ page_html|safe }}
            </ul>
        </nav>
    </div>
{% endblock %}